### ISSUE TITLE
change events to programs

### ISSUE THREAD

**Issue by tejasmanohar** [appupa/self-defense-texas#4]
http://selfdefensetexas.com/about_krav.html

and

http://selfdefensetexas.com/about_fitness.html

**Comment by tejasmanohar** [comment]
remember to include descriptions in those two blurbs under new programs section

http://selfdefensetexas.com/about_krav.html
http://selfdefensetexas.com/about_fitness.html

**Comment by tejasmanohar** [comment]
brief description in blurbs, we'll have extended pages like them later

**Comment by piedoom** [comment]
Should i just choose one of the paragraphs from each?  There is no overall description.

**Comment by tejasmanohar** [comment]
Yeah sure. They'll tweak as needed, just a bit to show

**Comment by piedoom** [comment]
Done.
